<?php

/**
 * Admin Touch by Mats Neander 
 *
 * Adds fastclick.js for faster clicks on touchdevices and touchpunch for drag and drop on touchdevices.
 * 
 * FastClick is maintained by Rowan Beentje, Matthew Caruana Galizia and Matthew Andrews at FT Labs. https://github.com/ftlabs/fastclick
 * Touch punch © 2011 David Furfero. http://touchpunch.furf.com/
 *	
 * 
 * ProcessWire 2.x 
 * Copyright (C) 2014 by Ryan Cramer 
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 * 
 * http://processwire.com
 *
 */

class AdminTouch extends WireData implements Module {

	/**
	 * getModuleInfo is a module required by all modules to tell ProcessWire about them
	 *
	 * @return array
	 *
	 */
	public static function getModuleInfo() {

		return array(

			// The module'ss title, typically a little more descriptive than the class name
			'title' => 'AdminTouch', 

			// version number 
			'version' => 1, 

			// summary is brief description of what this module is
			'summary' => 'Drag and drop and faster clicks for touch screens',
			
			// Optional URL to more information about the module
			'href' => '',

			// singular=true: indicates that only one instance of the module is allowed.
			// This is usually what you want for modules that attach hooks. 
			'singular' => true, 

			// autoload=true: indicates the module should be started with ProcessWire.
			// This is necessary for any modules that attach runtime hooks, otherwise those
			// hooks won't get attached unless some other code calls the module on it's own.
			// Note that autoload modules are almost always also 'singular' (seen above).
			'autoload' => true, 
		
			// Optional font-awesome icon name, minus the 'fa-' part
			'icon' => 'hand-o-up', 
			);
	}

	/**
	 * Initialize the module
	 *
	 * ProcessWire calls this when the module is loaded. For 'autoload' modules, this will be called
	 * when ProcessWire's API is ready. As a result, this is a good place to attach hooks. 
	 *
	 */
	public function init() {}

		public function ready() {
		 	if($this->page->template == 'admin'){ 
			    $this->addHookBefore('ProcessController::execute', $this, 'hookTouch'); 
				$this->addHookAfter('Page::render', $this, 'addFc');
			}
		}

		public function hookTouch(HookEvent $event) {
			
			$this->config->scripts->append( $this->config->urls->AdminTouch . "js/fastclick.js" );
			$this->config->scripts->append( $this->config->urls->AdminTouch . "js/jquery.ui.touch-punch.min.js" );
			$this->config->js($this->className());

			
		}

		public function addFc(HookEvent $event) {
			if($this->page->template == 'admin'){ 
				$page = $event->object; 				
				$script = "\n<script>$(function() {FastClick.attach(document.body);});</script>";
				$event->return = str_replace("</body>","$script</body>",$event->return);	
			}
		}





		
		
}


